pre_tasks:
      - name: Ensuring Homebrew Is Installed
        stat:
          path: /usr/local/bin/brew
        register: homebrew_check

      - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
        fail:
          msg: Homebrew is missing, install from http://brew.sh
        when:
          - not homebrew_check.stat.exists
          - not install_homebrew_if_missing

      - name: Installing Homebrew
        shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        when:
          - not homebrew_check.stat.exists
          - install_homebrew_if_missing

- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env' , 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - include: macos/core.yml
    - include: macos/ssh-setup.yml
    - include: macos/.dotfiles-setup.yml
    - include: macos/github-api.yml
    - include: macos/zsh-setup.yml
    - include: macos/node-setup.yml
    - include: macos/nvim-setup.yml
    - include: macos/docker-setup.yml
      #    - include: macos/brave-setup.yml
    - include: macos/java-setup.yml
    - include: macos/python-setup.yml
