- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["cmake", "pkg-config", "libfreetype6-dev", "libfontconfig1-dev", "libxcb-xfixes0-dev", "libxkbcommon-dev" ,"python3"]
  tags:
    - install
    - terminal
    - core

- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  tags:
    - install
    - terminal
    - core

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - install
    - terminal
    - core

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - install
    - terminal
    - core

- name: Clone alacritty
  ansible.builtin.git:
    repo: 'https://github.com/alacritty/alacritty.git'
    dest: "{{ lookup('env', 'HOME') }}/alacritty"
  tags:
    - install
    - terminal
    - core
- name: Install setup rustup to correct version
  shell: rustup override set stable && rustup update stable
  tags:
    - install
    - terminal
    - core
- name: Build alacritty
  shell: cd {{ lookup('env', 'HOME') }}/alacritty  && cargo build --release
  tags:
    - install
    - terminal
    - core
- name: Move alacritty to path and install
  shell: >
      cd {{ lookup('env', 'HOME') }}/alacritty &&
      cp target/release/alacritty /usr/local/bin &&
      cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg &&
      desktop-file-install extra/linux/Alacritty.desktop && sudo update-desktop-database
  become: true
  tags:
    - install
    - terminal
    - core


