- name: Update apt
  shell: apt update && apt upgrade -y
  become: true
- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - nvim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: [ "feh", "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - nvim
    - core
- name: Install System Packages 3
  become: true
  apt:
    name: ["lsb-release", "gnupg","curl"]
  tags:
    - core
    - install
    - docker
- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-11", "clangd-12"]
  tags:
    - install
    - nvim
    - core

- name: Install System Packages 4
  become: true
  apt:
    name: ["compton","nitrogen","jp", "compton", "htop", "lsof", "fzf", "tmux","i3", "blueman","ccache", "ninja-build", "python3-pip", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils", "clangd", "ubuntu-mate-desktop" ]
  tags:
    - install
    - core


