- name: Installing package
  shell: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
  tags:
    - install
    - dotfiles
    - stow
- name: echo keyrings
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  tags:
    - install
    - dotfiles
    - stow
- name: install gh
  shell: apt update && apt install gh
  become: true
  tags:
    - install
    - dotfiles
    - stow
