- name: Install Node
  become: true
  apt:
    name: ['nodejs', 'npm']
    update_cache: true
  tags:
   - node
   - install
- name: Install yarn
  become: true
  npm:
    name: yarn
    global: yes
  tags:
    - node
    - install
