# - name: Installing Homebrew Cask Packages
#   homebrew_cask:
#     name: "{{ brew_cask_packages }}"
#     state: present
#   register: result
#   until: result is successful

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: result
  until: result is successful
